#!/usr/bin/env python3
"""Render the check catalog from tools/workflow.json; --check proves it is current.

The catalog is a projection, not a second source of truth: `tools/workflow.json` owns
the surfaces and the checks, and this script turns them into one page a reader can
browse. The page is generated, never hand-edited, and its freshness gate is `--check`,
which re-renders the page and exits 1 when the committed file differs. Declare that
command on the `generated-docs` surface so `run-evidence` actually runs it.

Usage:
  python3 tools/gen-docs.py            # write docs/check-catalog.md
  python3 tools/gen-docs.py --check    # exit 1 when the committed page is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import NoReturn

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "tools" / "workflow.json"
TARGET = ROOT / "docs" / "check-catalog.md"


def die(message: str, code: int = 2) -> NoReturn:
    """Print a diagnostic to stderr and exit."""
    print(f"gen-docs: {message}", file=sys.stderr)
    raise SystemExit(code)


def load_config(path: Path) -> dict:
    """Read the surface and check declarations this page projects."""
    if not path.is_file():
        die(f"config not found: {path}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        die(f"cannot read config {path}: {exc}")
    if not isinstance(config, dict):
        die(f"config must be a JSON object: {path}")
    for field in ("surfaces", "checks"):
        if not isinstance(config.get(field), list) or not config[field]:
            die(f"config needs a non-empty {field!r} list: {path}")
    return config


def cell(value: object) -> str:
    """Render one table cell: escape the column separator and fold newlines."""
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def scope_cell(surface: dict) -> str:
    """Render a surface's scope: its patterns, minus the exclusions it declares.

    A surface claims `patterns` minus `exclude`; printing only the patterns would
    project a scope wider than the one change-scope applies.
    """
    scope = patterns_cell(surface.get("patterns", []))
    exclude = surface.get("exclude")
    if isinstance(exclude, list) and exclude:
        scope += " (except " + patterns_cell(exclude) + ")"
    return scope


def patterns_cell(patterns: list[str]) -> str:
    """Render a pattern list as one table cell."""
    return ", ".join(f"`{cell(pattern)}`" for pattern in patterns)


def render(config: dict) -> str:
    """Return the complete catalog page for the given configuration."""
    lines = [
        "# Check catalog (generated page)",
        "",
        "> Generated by `python3 tools/gen-docs.py`; never edit it by hand. Regenerate with "
        "`python3 tools/gen-docs.py`; freshness: `python3 tools/gen-docs.py --check`. The fact source is "
        "[tools/workflow.json](../tools/workflow.json).",
        "",
        "This page lists the changed surfaces and the gates this repository declares right now: a surface answers "
        "\"which evidence do I run after changing this path\", and a gate answers \"which convention turns red when it "
        "is violated\". Why each one exists, and what it gave up, lives in the decision records under "
        "[notes/](../notes/implemented/TEMPLATE.md); the decision logic is not restated here, only executed in "
        "[tools/check-invariants.py](../tools/check-invariants.py) and [tools/pair-docs.py](../tools/pair-docs.py).",
        "",
        "## Changed surfaces",
        "",
        "| Surface | Paths | Why it exists |",
        "|---|---|---|",
    ]
    for surface in config["surfaces"]:
        lines.append(
            f"| `{cell(surface.get('name', ''))}` | {scope_cell(surface)} "
            f"| {cell(surface.get('why', ''))} |",
        )
    lines += [
        "",
        "## Gates",
        "",
        "| Check | Kind | Paths | Why it exists |",
        "|---|---|---|---|",
    ]
    for check in config["checks"]:
        lines.append(
            f"| `{cell(check.get('id', ''))}` | `{cell(check.get('kind', ''))}` "
            f"| {patterns_cell(check.get('patterns', []))} | {cell(check.get('why', ''))} |",
        )
    lines += [
        "",
        "The surfaces are read by [tools/change-scope.py](../tools/change-scope.py) and "
        "[tools/run-evidence.py](../tools/run-evidence.py); the gates are executed by "
        "[tools/check-invariants.py](../tools/check-invariants.py) and [tools/pair-docs.py](../tools/pair-docs.py).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(
        prog="gen-docs",
        description="Render docs/check-catalog.md from tools/workflow.json.",
    )
    parser.add_argument("--check", action="store_true", help="exit 1 when the committed page is stale")
    args = parser.parse_args(argv)

    rendered = render(load_config(CONFIG))

    if args.check:
        committed = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else None
        if committed != rendered:
            detail = "does not exist" if committed is None else "differs from the rendered page"
            die(
                f"{TARGET.relative_to(ROOT)} {detail} — run `python3 tools/gen-docs.py` and commit the result",
                code=1,
            )
        print(f"gen-docs: {TARGET.relative_to(ROOT)} is up to date ({len(rendered.splitlines())} lines).")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"gen-docs: wrote {TARGET.relative_to(ROOT)} ({len(rendered.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
